Dial back to postcss-merge-rules@2.0.11 as 2.1.0+ breaks with an error like this:
BrowserslistError: Unknown browser query `op_mini all`
    at error (/path/to/node_modules/browserslist/index.js:23:15)
    at /path/to/node_modules/browserslist/index.js:124:13
    at Array.forEach (native)
    at browserslist (/path/to/node_modules/browserslist/index.js:96:16)
    at isSupported (/path/to/node_modules/caniuse-api/dist/index.js:75:10)
    at /path/to/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:87:66
    at /path/to/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26

(cherry picked from commit db2bbacb05e6a080c6f95cff3d70868021b58e15)